  - name: installing mysql server
    ansible.builtin.dnf:
     name: mysql-server
     state: present

  - name: Enabling and starting mysql server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: true

  - name: setp root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ ANSIBLE_ROOT_PASSWORD }}"
