- name: install maven software
  ansible.builtin.dnf:
    name: maven
    state: present

- name: install PyMySQL and cryptography 
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL   

- name: Downloading the dependencies
  ansible.builtin.command: mvn clean package 
  args:
    chdir: /app   

- name: "cut and rename target/shipping-1.0.jar to shipping.jar"
  ansible.builtin.command: "mv target/shipping-1.0.jar shipping.jar"
  args:
    chdir: /app