- name: setting up system_d service to be managed by systemctl
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: /etc/systemd/system/{{ component }}.service

- name: loading the systemd service
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: enable and restart the systemctl service
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes